AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'starbucks_events without APIgateway customize Sample SAM Template for
  starbucks_events'
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://huro3h2020-lambda-function/bc4794e645d4a03f59cc4d02cd96825e
      Handler: app.lambda_handler
      Runtime: ruby2.5
Outputs:
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
