AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'starbucks_events without APIgateway customize Sample SAM Template for
  starbucks_events'
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://huro3h-lambda-function/bc14ee6802fbaf25fdef180f0ef75935
      Handler: app.lambda_handler
      Runtime: ruby2.5
Outputs:
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
