AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'starbucks_events

  Sample SAM Template for starbucks_events

  '
Globals:
  Function:
    Runtime: ruby2.5
    Timeout: 15
    MemorySize: 256
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://huro3h2020-lambda-function/19681ba653b5f135a9e9bf2e3007eb67
      Handler: app.handler
Outputs:
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
