AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  starbucks_events without APIgateway customize
  Sample SAM Template for starbucks_events
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      # Events:
      #   HelloWorld:
      #     Type: Api
      #     Properties:
      #       Path: /stage3
      #       Method: post

Outputs:
  HelloWorldFunction:
  Description: "Hello World Lambda Function ARN"
  Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/stage3/"
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
